const topMovies = [
    { title: "The Dark Knight", genre: "Action", duration: "Long", mood: "Excited", watchtime: 152, platform: "Netflix", link: "https://www.netflix.com/title/thedarkknight" },
    { title: "Inception", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 148, platform: "Amazon Prime", link: "https://www.primevideo.com/title/inception" },
    { title: "The Hangover", genre: "Comedy", duration: "Medium", mood: "Happy", watchtime: 100, platform: "HBO Max", link: "https://www.hbomax.com/title/thehangover" },
    { title: "Forrest Gump", genre: "Drama", duration: "Long", mood: "Relaxed", watchtime: 142, platform: "Paramount+", link: "https://www.paramountplus.com/title/forrestgump" },
    { title: "The Conjuring", genre: "Horror", duration: "Medium", mood: "Excited", watchtime: 112, platform: "HBO Max", link: "https://www.hbomax.com/title/theconjuring" },
    { title: "Interstellar", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 169, platform: "Amazon Prime", link: "https://www.primevideo.com/title/interstellar" },
    { title: "The Avengers", genre: "Action", duration: "Long", mood: "Excited", watchtime: 143, platform: "Disney+", link: "https://www.disneyplus.com/title/theavengers" },
    { title: "The Matrix", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 136, platform: "HBO Max", link: "https://www.hbomax.com/title/thematrix" },
    { title: "Deadpool", genre: "Comedy", duration: "Medium", mood: "Excited", watchtime: 108, platform: "Hulu", link: "https://www.hulu.com/title/deadpool" },
    { title: "Shutter Island", genre: "Drama", duration: "Medium", mood: "Relaxed", watchtime: 138, platform: "Amazon Prime", link: "https://www.primevideo.com/title/shutterisland" },
    { title: "The Shining", genre: "Horror", duration: "Long", mood: "Excited", watchtime: 146, platform: "HBO Max", link: "https://www.hbomax.com/title/theshining" },
    { title: "The Lion King", genre: "Drama", duration: "Medium", mood: "Happy", watchtime: 88, platform: "Disney+", link: "https://www.disneyplus.com/title/thelionking" },
    { title: "Avengers: Endgame", genre: "Action", duration: "Long", mood: "Excited", watchtime: 181, platform: "Disney+", link: "https://www.disneyplus.com/title/avengersendgame" },
    { title: "Jumanji", genre: "Comedy", duration: "Medium", mood: "Happy", watchtime: 104, platform: "Amazon Prime", link: "https://www.primevideo.com/title/jumanji" },
    { title: "Spider-Man: No Way Home", genre: "Action", duration: "Long", mood: "Excited", watchtime: 148, platform: "Disney+", link: "https://www.disneyplus.com/title/spidermannowayhome" },
    { title: "The Pursuit of Happyness", genre: "Drama", duration: "Medium", mood: "Happy", watchtime: 117, platform: "Netflix", link: "https://www.netflix.com/title/thepursuitofhappyness" },
    { title: "Scream", genre: "Horror", duration: "Medium", mood: "Excited", watchtime: 111, platform: "Paramount+", link: "https://www.paramountplus.com/title/scream" },
    { title: "Jurassic Park", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 127, platform: "Peacock", link: "https://www.peacocktv.com/title/jurassicpark" },
    { title: "Zombieland", genre: "Comedy", duration: "Medium", mood: "Excited", watchtime: 88, platform: "Hulu", link: "https://www.hulu.com/title/zombieland" },
    { title: "The Godfather", genre: "Drama", duration: "Long", mood: "Relaxed", watchtime: 175, platform: "Paramount+", link: "https://www.paramountplus.com/title/thegodfather" },
    { title: "Toy Story", genre: "Comedy", duration: "Medium", mood: "Happy", watchtime: 81, platform: "Disney+", link: "https://www.disneyplus.com/title/toystory" },
    { title: "Star Wars: A New Hope", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 121, platform: "Disney+", link: "https://www.disneyplus.com/title/starwarsanewhope" },
    { title: "The Matrix Reloaded", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 138, platform: "HBO Max", link: "https://www.hbomax.com/title/thematrixreloaded" },
    { title: "The Silence of the Lambs", genre: "Horror", duration: "Medium", mood: "Excited", watchtime: 118, platform: "Hulu", link: "https://www.hulu.com/title/thesilenceofthelambs" },
    { title: "Mission: Impossible – Fallout", genre: "Action", duration: "Long", mood: "Excited", watchtime: 147, platform: "Paramount+", link: "https://www.paramountplus.com/title/missionimpossiblefallout" },
    { title: "Deadpool 2", genre: "Comedy", duration: "Medium", mood: "Excited", watchtime: 119, platform: "Hulu", link: "https://www.hulu.com/title/deadpool2" },
    { title: "Gladiator", genre: "Action", duration: "Long", mood: "Adventurous", watchtime: 155, platform: "Netflix", link: "https://www.netflix.com/title/gladiator" },
    { title: "The Wolf of Wall Street", genre: "Comedy", duration: "Long", mood: "Excited", watchtime: 180, platform: "Amazon Prime", link: "https://www.primevideo.com/title/thewolfofwallstreet" },
    { title: "A Quiet Place", genre: "Horror", duration: "Medium", mood: "Excited", watchtime: 90, platform: "Paramount+", link: "https://www.paramountplus.com/title/aquietplace" },
    { title: "The Shawshank Redemption", genre: "Drama", duration: "Long", mood: "Relaxed", watchtime: 142, platform: "Netflix", link: "https://www.netflix.com/title/theshawshankredemption" },
    { title: "Back to the Future", genre: "Sci-Fi", duration: "Medium", mood: "Adventurous", watchtime: 116, platform: "Amazon Prime", link: "https://www.primevideo.com/title/backtothefuture" },
    { title: "Guardians of the Galaxy", genre: "Action", duration: "Medium", mood: "Excited", watchtime: 121, platform: "Disney+", link: "https://www.disneyplus.com/title/guardiansofthegalaxy" },
    { title: "It", genre: "Horror", duration: "Long", mood: "Excited", watchtime: 135, platform: "HBO Max", link: "https://www.hbomax.com/title/it" },
    { title: "The Social Network", genre: "Drama", duration: "Medium", mood: "Relaxed", watchtime: 120, platform: "Netflix", link: "https://www.netflix.com/title/thesocialnetwork" },
    { title: "Iron Man", genre: "Action", duration: "Medium", mood: "Excited", watchtime: 126, platform: "Disney+", link: "https://www.disneyplus.com/title/ironman" },
    { title: "The Secret Life of Walter Mitty", genre: "Drama", duration: "Medium", mood: "Happy", watchtime: 114, platform: "Amazon Prime", link: "https://www.primevideo.com/title/thesecretlifeofwaltermitty" },
    { title: "The Hunger Games", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 142, platform: "Peacock", link: "https://www.peacocktv.com/title/thehungergames" },
    { title: "The Great Gatsby", genre: "Drama", duration: "Medium", mood: "Relaxed", watchtime: 143, platform: "HBO Max", link: "https://www.hbomax.com/title/thegreatgatsby" },
    { title: "Mad Max: Fury Road", genre: "Action", duration: "Long", mood: "Excited", watchtime: 120, platform: "HBO Max", link: "https://www.hbomax.com/title/madmaxfuryroad" },
    { title: "How to Train Your Dragon", genre: "Comedy", duration: "Medium", mood: "Happy", watchtime: 98, platform: "Amazon Prime", link: "https://www.primevideo.com/title/howtotrainyourdragon" },
    { title: "The Exorcist", genre: "Horror", duration: "Long", mood: "Excited", watchtime: 122, platform: "HBO Max", link: "https://www.hbomax.com/title/theexorcist" },
    { title: "Pirates of the Caribbean", genre: "Action", duration: "Long", mood: "Adventurous", watchtime: 143, platform: "Disney+", link: "https://www.disneyplus.com/title/piratesofthecaribbean" },
    { title: "Trainspotting", genre: "Drama", duration: "Medium", mood: "Relaxed", watchtime: 93, platform: "Hulu", link: "https://www.hulu.com/title/trainspotting" },
    { title: "The Incredibles", genre: "Comedy", duration: "Medium", mood: "Excited", watchtime: 115, platform: "Disney+", link: "https://www.disneyplus.com/title/theincredibles" },
    { title: "E.T. the Extra-Terrestrial", genre: "Sci-Fi", duration: "Medium", mood: "Adventurous", watchtime: 115, platform: "Peacock", link: "https://www.peacocktv.com/title/et" },
    { title: "A Nightmare on Elm Street", genre: "Horror", duration: "Medium", mood: "Excited", watchtime: 91, platform: "HBO Max", link: "https://www.hbomax.com/title/anightmareonelmstreet" },
    { title: "The Prestige", genre: "Drama", duration: "Long", mood: "Relaxed", watchtime: 130, platform: "Amazon Prime", link: "https://www.primevideo.com/title/theprestige" },
    { title: "Alien", genre: "Sci-Fi", duration: "Long", mood: "Adventurous", watchtime: 117, platform: "HBO Max", link: "https://www.hbomax.com/title/alien" }

]

